#!/bin/bash

export DAYS=40
export MIN_COOKS=8
export MAX_COOKS=20
export COOKS_INTERVAL=3
export WAITERS_COUNT=10
export TABLES_COUNT=50
export INITIAL_POPULARITY=10
export COOK_SALARY=80.0

./question2.rb | ./question2_viz.py
