#!/bin/bash

export DAYS=50
export MIN_COOKS=1
export MAX_COOKS=15
export COOKS_INTERVAL=2
export WAITERS_COUNT=10
export TABLES_COUNT=20
export INITIAL_POPULARITY=10
export COOK_SALARY=80.0

./question2.rb | ./question2_viz.py
