#!/bin/bash

export DAYS=100
export COOKS_COUNT=1
export WAITERS_COUNT=10
export TABLES_COUNT=100000
export INITIAL_POPULARITY=100
export COOK_SALARY=80.0
export SHOW_STATS=0

./main.rb | ./plot_1.py
