#!/bin/bash

export DAYS=360
export MIN_COOKS=1
export MAX_COOKS=6
export COOKS_INTERVAL=1
export WAITERS_COUNT=1
export TABLES_COUNT=10
export INITIAL_POPULARITY=10
export COOK_SALARY=15.0

./question2.rb | ./question2_viz.py
